name: Auto release
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 22.17.0

    - name: Corepack
      run: corepack enable
    
    - name: Install dependencies
      run: yarn install
    
    - name: Auto release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: yarn auto-release
      